### PR TITLE
Fix compatibility with 1.5

### PR DESCRIPTION
**Pull request by AamuLumi**
Hey,

I test the `master` branch with the 1.5 version, and I got some errors caused by modifications of `Dialog_Rename` code in the update.

Errors are fixed, and you should be able to build the mod for 1.5. Don't forget to update the Rimworld NuGet package, I didn't add the change because my .sln is a bit messy.

I quickly tested the mod in the dev sandbox test, and pawns were able to carry food in the good furniture.
I recommend to you to do a bit more tests before considering the mod is fully compatible with 1.5.

Thanks a lot for your mod, it's probably one of my favourite mods. <3

PS : the code added in `CompDeepStorage` is the one used in the `Verse.CompAnimalPenMarker`. I didn't know exactly what's the behavior of these new labels.

### CODE REVIEW

**Comment by lilwhitemouse** [comment]
Awesome, thank you! I was hoping someone might do this. I'll try and get it all put together in the next day or so

**Comment by AamuLumi** [comment]
Hey LWM ! No problem, happy to see you !

I also fixed the Gizmo patch because the IL changed and caused some mod loading crash.
Everything should be fine for the 1.5.

Tell me when everything is good for a publication on your side, I'll redirect everyone to the official mod.

**Comment by ThisIsSP4RTAN** [comment]
One thing I noticed while replacing the 900+ wall lights in my 1.4 save to the new wall lamps is that it's basically impossible to select the wall lamp if it's on a wall that's right next to a deep storage building without using the "select similar" tool. Not sure if it's something that can be changed or not.

2024-04-1414-10-44-ezgif com-video-to-gif-converter

**Comment by AamuLumi** [comment]
The last commit comes from a message from @just-harry on Steam (current maintenant of RimFridge).
The DeepStorage patch for RimFridge add a Deep Refrigerator. This building use the base RimFridge class, but RimFridge already have done the transition to `groupingLabel` API from 1.5. So the building is blocking the feature "Take to XXX" in any workshops caused by the missing `groupingLabel` on the XML.

I also added #151 to fully implement these features in DeepStorage mod, but it's not needed for migrating the mod to the 1.5. So I added only the important fix.

@ThisIsSP4RTAN : I reproduced the problem, and I don't know why Tynan decided to not get the old system from the Wall Light mod. This is not a problem from Deep Storage : the light seems on the wall, but it's on the cell in front of the light. So you have to click, wait 400ms and click again to select the lamp (the exact process when you have multiple items on a cell and you want to select the one behind). Maybe someone will find a fix for that in the future, but this is out of DeepStorage.

**Comment by lilwhitemouse** [comment]
Now I just need to clean up the actual merge, because it's broken AF right now

**Comment by AamuLumi** [comment]
I can take a look to the code during this week-end if you need.

**Pull request merged**
