### PR TITLE
Compatibility Patches

### PR DESCRIPTION
**Pull request by DrZhivago1**
Rim of Madness - Bones
RimCuisine
[XND] Survival Tools

### CODE REVIEW

**Comment by lilwhitemouse** [comment]
What's the stack size for prepared foods; is it also 75?

**Comment by DrZhivago1** [comment]
I believe there is no change to stack sizes with "RimCuisine" or "Rim of Madness-Bones". 

Where did you get your info on "/Defs" being faster? It is my understanding that /Defs is actually (negligibly) slower. Some info on it here: https://www.reddit.com/r/RimWorld/comments/7gys9p/psa_about_xpath_in_patchesmods/ . As well as the general consensus with the other modders I've spoken with through the Discord and Ludeon.

**Comment by lilwhitemouse** [comment]
1, that link didn't give any methodology, as far as I can tell?  So I'm not sure how they got there numbers.
2, I read up on the specs for xpath - starting at /def makes more sense for any search algorithm I know; conversely, if you have to search MORE definitions (which you do with Defs/&c, because it could be /Defs/ThingDefs/WeirdThingDef/ContaineDefs/Defs/Etc, which would match Defs/Etc...), it logically would take more time?
3, https://github.com/lilwhitemouse/RimWorld-PatchSpeedTest   - this included the delightful tidbit that whichever test I ran first finished faster.  Caching getting slower as more tests are run?  Who knows.  But that might be what was going on with the other person's test?  Anyway, overall, I see /Defs/&c slightly faster.

Falling asleep, so hope that made sense, hope I didn't come across as cross or anything ^.^

I'm leaning super heavily towards processedfoods going on the meal racks, for lack of a better shelf?  Alternately, I'm thinking to create a bigger shelf for things like hay, and that might work?

**Comment by DrZhivago1** [comment]
Nah, not cross. I was just curious about your reasoning. My link doesn't give much reasoning to it, but yea just a visual. It's a pretty negligible difference anyway.

It's kinda 50/50 with the "Processed Ingredients" from RimCuisine. Like sugar ain't a meal, but fruit preserves could be. Maybe it'd be wiser to just add "Processed ingredients" category to both meal racks and food baskets, then let the users figure out what they wanna do.

As for adding the hay to food baskets/getting new storage... The main reason I include hay in my food basket is for uniformity in the freezer. But having some animal basket or sack or shelving could be neat. Holding raw ingredients, kibble, hay, pemmican.

**Comment by lilwhitemouse** [comment]
"Maybe it'd be wiser to just add "Processed ingredients" category to both meal racks and food baskets, then let the users figure out what they wanna do."

Okay, can't argue with that one!

**Pull request merged**
